# ============================================
# Super Agent Configuration
# ============================================
# The Super Agent acts as the orchestration layer that:
# - Triages user intent before planning
# - Decides whether to answer directly or handoff to Planner
# - Provides initial query enrichment and context gathering
# ============================================
# Configuration Priority (highest to lowest):
# 1. Environment Variables (highest priority)
# 2. .env file 
# 3. YAML files (lowest priority, system defaults)
# ============================================

name: "Super Agent"
enabled: true

# Model Configuration
# Super Agent typically needs a capable reasoning model
models:
  # Primary model for triage, reasoning, and query enrichment
  primary:
    model_id: "anthropic/claude-haiku-4.5"
    provider: "openrouter"  # Can be: openrouter, siliconflow, or null (uses system primary_provider)



  

# Environment Variable Overrides
# Format: ENV_VAR_NAME -> config.path
# These allow runtime configuration through environment variables
env_overrides:
  # Primary model overrides
  PLANNER_MODEL_ID: "models.primary.model_id"
  SUPER_AGENT_MODEL_ID: "models.primary.model_id"  # Alias for clarity
  SUPER_AGENT_PROVIDER: "models.primary.provider"
  SUPER_AGENT_TEMPERATURE: "models.primary.parameters.temperature"
  SUPER_AGENT_MAX_TOKENS: "models.primary.parameters.max_tokens"

# Super Agent Capabilities
capabilities:
  # Enable web search for context enrichment
  web_search: true
  
  # Enable crawling capabilities
  web_crawl: true
  
  # Session management
  session_management:
    enabled: true
    max_history_runs: 5
    enable_summaries: true

# Advanced Settings
advanced:
  # Debug mode (can be overridden by AGENT_DEBUG_MODE env var)
  debug_mode: false
  
  # Output format
  use_json_mode: true
  markdown: false
  
  # Context settings
  add_datetime_to_context: true
  add_history_to_context: true
  read_chat_history: true

