"""API schemas package."""

from .base import (
    StatusCode,
    BaseResponse,
    SuccessResponse,
    ErrorResponse,
    AppInfoData,
    HealthCheckData,
)
from .i18n import (
    I18nConfigData,
    SupportedLanguage,
    SupportedLanguagesData,
    TimezoneInfo,
    TimezonesData,
    LanguageRequest,
    TimezoneRequest,
    LanguageDetectionRequest,
    TranslationRequest,
    DateTimeFormatRequest,
    NumberFormatRequest,
    CurrencyFormatRequest,
    UserI18nSettingsData,
    UserI18nSettingsRequest,
    AgentI18nContextData,
    LanguageDetectionData,
    TranslationData,
    DateTimeFormatData,
    NumberFormatData,
    CurrencyFormatData,
)

__all__ = [
    # Base schemas
    "StatusCode",
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "AppInfoData",
    "HealthCheckData",
    # I18n schemas
    "I18nConfigData",
    "SupportedLanguage",
    "SupportedLanguagesData",
    "TimezoneInfo",
    "TimezonesData",
    "LanguageRequest",
    "TimezoneRequest",
    "LanguageDetectionRequest",
    "TranslationRequest",
    "DateTimeFormatRequest",
    "NumberFormatRequest",
    "CurrencyFormatRequest",
    "UserI18nSettingsData",
    "UserI18nSettingsRequest",
    "AgentI18nContextData",
    "LanguageDetectionData",
    "TranslationData",
    "DateTimeFormatData",
    "NumberFormatData",
    "CurrencyFormatData",
]
