"""API schemas package."""

from .base import (
    AppInfoData,
    BaseResponse,
    ErrorResponse,
    HealthCheckData,
    StatusCode,
    SuccessResponse,
)
from .i18n import (
    AgentI18nContextData,
    CurrencyFormatData,
    CurrencyFormatRequest,
    DateTimeFormatData,
    DateTimeFormatRequest,
    I18nConfigData,
    LanguageDetectionData,
    LanguageDetectionRequest,
    LanguageRequest,
    NumberFormatData,
    NumberFormatRequest,
    SupportedLanguage,
    SupportedLanguagesData,
    TimezoneInfo,
    TimezoneRequest,
    TimezonesData,
    TranslationData,
    TranslationRequest,
    UserI18nSettingsData,
    UserI18nSettingsRequest,
)
from .watchlist import (
    AddStockRequest,
    AssetDetailData,
    AssetHistoricalPriceData,
    AssetHistoricalPricesData,
    AssetInfoData,
    AssetPriceData,
    AssetSearchQuery,
    AssetSearchResultData,
    CreateWatchlistRequest,
    UpdateStockNotesRequest,
    WatchlistData,
    WatchlistItemData,
    WatchlistWithPricesData,
)

__all__ = [
    # Base schemas
    "StatusCode",
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "AppInfoData",
    "HealthCheckData",
    # I18n schemas
    "I18nConfigData",
    "SupportedLanguage",
    "SupportedLanguagesData",
    "TimezoneInfo",
    "TimezonesData",
    "LanguageRequest",
    "TimezoneRequest",
    "LanguageDetectionRequest",
    "TranslationRequest",
    "DateTimeFormatRequest",
    "NumberFormatRequest",
    "CurrencyFormatRequest",
    "UserI18nSettingsData",
    "UserI18nSettingsRequest",
    "AgentI18nContextData",
    "LanguageDetectionData",
    "TranslationData",
    "DateTimeFormatData",
    "NumberFormatData",
    "CurrencyFormatData",
    # Watchlist schemas
    "WatchlistItemData",
    "WatchlistData",
    "CreateWatchlistRequest",
    "AddStockRequest",
    "UpdateStockNotesRequest",
    "AssetSearchQuery",
    "AssetInfoData",
    "AssetSearchResultData",
    "AssetDetailData",
    "AssetPriceData",
    "AssetHistoricalPriceData",
    "AssetHistoricalPricesData",
    "WatchlistWithPricesData",
]
