"""API schemas package."""

from .base import (
    AppInfoData,
    BaseResponse,
    ErrorResponse,
    HealthCheckData,
    StatusCode,
    SuccessResponse,
)
from .conversation import (
    ConversationListData,
    ConversationListItem,
    ConversationListResponse,
)
from .i18n import (
    AgentI18nContextData,
    CurrencyFormatData,
    CurrencyFormatRequest,
    DateTimeFormatData,
    DateTimeFormatRequest,
    I18nConfigData,
    LanguageDetectionData,
    LanguageDetectionRequest,
    LanguageRequest,
    NumberFormatData,
    NumberFormatRequest,
    SupportedLanguage,
    SupportedLanguagesData,
    TimezoneInfo,
    TimezoneRequest,
    TimezonesData,
    TranslationData,
    TranslationRequest,
    UserI18nSettingsData,
    UserI18nSettingsRequest,
)
from .user_profile import (
    CreateUserProfileRequest,
    UpdateUserProfileRequest,
    UserProfileData,
    UserProfileListData,
    UserProfileSummaryData,
)
from .watchlist import (
    AddAssetRequest,
    AssetDetailData,
    AssetHistoricalPriceData,
    AssetHistoricalPricesData,
    AssetInfoData,
    AssetPriceData,
    AssetSearchQuery,
    AssetSearchResultData,
    CreateWatchlistRequest,
    UpdateAssetNotesRequest,
    WatchlistData,
    WatchlistItemData,
    WatchlistWithPricesData,
)

__all__ = [
    # Base schemas
    "StatusCode",
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "AppInfoData",
    "HealthCheckData",
    # I18n schemas
    "I18nConfigData",
    "SupportedLanguage",
    "SupportedLanguagesData",
    "TimezoneInfo",
    "TimezonesData",
    "LanguageRequest",
    "TimezoneRequest",
    "LanguageDetectionRequest",
    "TranslationRequest",
    "DateTimeFormatRequest",
    "NumberFormatRequest",
    "CurrencyFormatRequest",
    "UserI18nSettingsData",
    "UserI18nSettingsRequest",
    "AgentI18nContextData",
    "LanguageDetectionData",
    "TranslationData",
    "DateTimeFormatData",
    "NumberFormatData",
    "CurrencyFormatData",
    # Conversation schemas
    "ConversationListData",
    "ConversationListItem",
    "ConversationListResponse",
    # Watchlist schemas
    "WatchlistItemData",
    "WatchlistData",
    "CreateWatchlistRequest",
    "AddAssetRequest",
    "UpdateAssetNotesRequest",
    "AssetSearchQuery",
    "AssetInfoData",
    "AssetSearchResultData",
    "AssetDetailData",
    "AssetPriceData",
    "AssetHistoricalPriceData",
    "AssetHistoricalPricesData",
    "WatchlistWithPricesData",
    # User Profile schemas
    "UserProfileData",
    "CreateUserProfileRequest",
    "UpdateUserProfileRequest",
    "UserProfileListData",
    "UserProfileSummaryData",
]
